Sequence plot
brain-link/scanhub-ui pull request #12
Opened 2023-06-14 04:50 UTC by schote

- Reimplementation of sequence plot as full-screen plot
- Request plot via sequence-manager endpoint

Todo:

- [ ] upload new sequence
- [ ] show sequence meta information

<img width="1489" alt="Bildschirmfoto 2023-06-14 um 00 47 32" src="https://github.com/brain-link/scanhub-ui/assets/42237900/b35e01a5-b41c-47ad-9e54-f588da570fe4">

2023-07-25 22:00 UTC, schote commented
<img width="376" alt="Bildschirmfoto 2023-07-25 um 23 58 43" src="https://github.com/brain-link/scanhub-ui/assets/42237900/b0be8a96-cba6-4c61-ad01-eef3ed4c39b1">

Sequence meta information next to sequence plot (excerpt)

2023-07-26 20:02 UTC, chdinh requested changes

2023-07-26 20:02 UTC, chdinh commented on frontend/src/interfaces/components.interface.tsx
> +// import { Workflow } from './data.interface';
obsolete import?

2023-07-26 20:02 UTC, chdinh commented on frontend/src/interfaces/components.interface.tsx
> +    data: Job;
data for job is rather unsepcific var naming - why not keeoping it job or jobDescription, jobInstance

2023-07-26 20:02 UTC, chdinh commented on frontend/src/interfaces/data.interface.tsx
> +    site: string | null;
having too little TS knowledge however "?" removed where it was added below?

2023-07-27 20:41 UTC, schote commented on frontend/src/client/sequence-api.tsx
> +    // TODO: Needs to be tested
The todo will be covered in a separate PR

2023-07-27 20:45 UTC, schote commented on frontend/src/components/jobs/JobList.tsx
> +// import { Workflow } from '../../interfaces/data.interface';
These are placeholders. They will be used as soon as device and workflow api are ready.

2023-07-27 20:45 UTC, schote commented on frontend/src/components/jobs/JobList.tsx
> +    // });
See comment above, also a placeholder.

2023-07-27 20:46 UTC, schote commented on frontend/src/interfaces/components.interface.tsx
> +// import { Workflow } from './data.interface';
See above.

2023-07-27 20:48 UTC, schote commented on frontend/src/interfaces/data.interface.tsx
> +    site: string | null;
"?" means optional, since this property can be null, this is redundant

2023-07-27 20:51 UTC, schote commented on frontend/src/interfaces/components.interface.tsx
> +    data: Job;
I renamed it to "data" for consistency to the generic "ComponentProps" interface. Data means content of the job and it is specified by its type "Job". However, we could also use "jobData" if this is not convinving.

2023-07-29 08:15 UTC, chdinh approved these changes

2023-07-29 08:15 UTC, merged